carbon_calculator/urls.py
from django.urls import path

from . import views

app_name = 'carbon_calculator'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('eventcalculator', views.eventcalculator, name='eventcalculator'),
    path('stations/', views.StationsView.as_view(), name='stations'),
    path('stations/<int:pk>', views.StationDetailView.as_view(), name='station-detail'),
    #path('stations', views.stations, name='stations'),
    #path('stationdetail', views.stationdetail, name='stationdetail'),
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('calculator/', include('carbon_calculator.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

carbon_calculator/models.py
# from django.db import models
from datetime import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    contact = models.EmailField()

class Sponsor(Organization):
    pass

class Organizer(Organization):
    pass

class Community(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length = 80)
    location = models.CharField(max_length = 80)
    date = models.DateTimeField()
    organizer = models.ForeignKey(Organizer, on_delete=models.PROTECT)
    sponsor = models.ForeignKey(Sponsor, on_delete=models.PROTECT)

class Person(models.Model):
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)    
    firstName = models.CharField(max_length = 20)
    lastName = models.CharField(max_length = 20)
    address = models.CharField(max_length = 50, default = "")
    community = models.CharField(max_length = 30)
    email = models.EmailField()
    phone = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    age_acknowledgment = models.BooleanField()

class Team(models.Model):
    name = models.CharField(max_length=40)
    members = models.IntegerField(default=0)
    carbon_points = models.FloatField(default=0.0)
    dollar_savings = models.FloatField(default=0.0)

#    teams = RelationshipTo('Team', 'IS_MEMBER', cardinality=ZeroOrMore)


#class Volunteer(Person):
 #   affiliation = Organization()

class Attendee(Person):
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    carbon_points = models.FloatField(default=0.0)
    dollar_savings = models.FloatField(default=0.0)

#class Vendor(Person)
#    company = StringProperty()
#    station = RelationshipTo('Station','HAS_STATION', cardinality=ZeroOrOne)

#class Team(models.Model):
#    members = RelationshipTo('Person', 'HAS_MEMBER', cardinality=ZeroOrMore)

class Station(models.Model):
    name = models.CharField(max_length = 20)
    number = models.IntegerField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    description = models.CharField(max_length = 200)
#    questions = RelationshipTo('Question', 'HAS_QUESTION', cardinality=ZeroOrMore)
    def __str__(self):
        return self.name
 
class Question(models.Model):
    question_text = models.CharField(max_length=20)
    description = models.CharField(max_length= 200)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    questionId = models.IntegerField(default = 0)
    response_type = models.CharField(max_length=10)
    choices = models.CharField(max_length=40)
#    calculatorVariable = RelationshipTo('CalculatorVariable','HAS_VARIABLE',cardinality=ZeroOrOne)
    def __str__(self):
        return self.question_text


    #population = models.IntegerField()
    #members = model.IntegerField()

#class Choice(models.Model):
#    question = models.ForeignKey(Question, on_delete=models.CASCADE)
#    choice_text = models.CharField(max_length=200)
#    def __str__(self):
#        return self.choice_text

#class Calculation(models.Model):
#    calculatorVariables = RelationshipTo('CalculatorVariable','USES_VARIABLE',cardinality = OneOrMore)
#    calculatorMethod = RelationshipTo()

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        as_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

carbon_calculator/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.db import models
from django.views import generic
from .estimator import Estimator
import datetime
import calendar

from pprint import pprint

#from django.views import generic
import logging

from .forms import NameForm, ContactForm, ExampleForm,StationDetailForm
from .models import Event, Attendee, Organizer, Sponsor, Station, Question, Community

event_name = 'Cooler Communities Event Calculator'
stationList = []
next_station = 1
estimator = Estimator()

# Create your views here.
def index(request):
    global event_name  
    event_name = estimator.GetEventName()
   
    # see if event is in database, if not, add it
    event = Event.objects.filter(name=event_name)
    if len(event)==0:

        datestring = estimator.GetEventDate()
        year = int(datestring[-4:])
        month = list(calendar.month_abbr).index(datestring[0:3])
        day = int(datestring[4:6])
        date = datetime.datetime(year, month, day)


        location= estimator.GetEventLocation()

        # add organizer if missing
        organizer_name = estimator.GetEventOrganizer()
        organizer = Organizer.objects.filter(name=organizer_name)
        if len(organizer)==0:
            organizer= Organizer(name=organizer_name)
            organizer.save()
        else:
            organizer = organizer.get(name=organizer_name)
        # add sponsor if missing
        sponsor_name = estimator.GetEventSponsor()
        sponsor = Sponsor.objects.filter(name=sponsor_name)
        if len(sponsor)==0:
            sponsor= Sponsor(name=sponsor_name)
            sponsor.save()
        else:
            sponsor = sponsor.get(name=sponsor_name)

        event = Event(name=event_name, date=date, location=location,organizer=organizer,sponsor=sponsor)
        event.save()
    
    welcome_context = {'EVENT_NAME':event_name}
    return render(request, 'carbon_calculator/welcome.html', welcome_context)
 
def about(request):
    global event_name
    event_name = estimator.GetEventName()
    about_context = {'EVENT_NAME':event_name}
    return render(request, 'carbon_calculator/about.html',about_context)

def eventcalculator(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            firstName = form.cleaned_data['firstName']
            lastName = form.cleaned_data['lastName']
            email = form.cleaned_data['email']
            address = form.cleaned_data['address']
            community = form.cleaned_data['community']
            phone = form.cleaned_data['phone']
            old_enough = form.cleaned_data['old_enough']

            matchingCommunities = Community.objects.filter(name=community)
            if len(matchingCommunities)==0:
                community = Community(name = community)
            else:
                community = matchingCommunities.get()

            if (old_enough[0]!='Y') and (old_enough[0]!='y'):
                age_acknowledgement=False
                firstName = "Underage"
                lastName = "Person"
                email = ""
                address = ""
                phone = ""
            else:
                age_acknowledgement=True
                attendee = Attendee.objects.filter(email=email)

            event = Event.objects.all()
            event_name = estimator.GetEventName()
            if len(event)>0:
                event = event.get(name=event_name)

            if lastName=="Person" or len(attendee)==0:
                attendee = Attendee(firstName=firstName, lastName=lastName, email=email,address=address,community=community,
                    phone=phone,age_acknowledgment=age_acknowledgement,event=event)
                attendee.save() 



 #           nameUpdateRequest = {"responseRanges":['Carbon Points Estimator!G4'],
 #                               "includeSpreadsheetInResponse": True,
 #                               "responseIncludeGridData": False,
 #                               "requests": [{"updateCells": {"range":'Carbon Points Estimator!B4:B11',"rows": }}],
 #                               }
 #           result = sheet.batchUpdate(spreadsheetId=settings.SPREADSHEET_ID,body=nameUpdateRequest)

            # redirect to a new URL:
            return HttpResponseRedirect('stations')
        else:
            print('Form not valid, POST')
            return HttpResponseRedirect('/Form not valid on POST/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'carbon_calculator/eventcalculator.html', {'form': form})

class StationsView(generic.ListView):
    model = Station
    template_name = 'carbon_calculator/stations.html'
    context_object_name = 'station_list'

    def __init__(self):
        station_list = estimator.GetStations()
        print('StationsView init, number of stations is '+str(len(station_list)))

        event = Event.objects.get(name=estimator.GetEventName())

        for i in range(len(stationList)):
            station = Station.objects.filter(name=stationList[i]).filter(event=event)
            if (len(station))==0:
                station=Station(name=station_list[i],number=i+1,event=event)
                station.save()

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        event = Event.objects.get(name=estimator.GetEventName())
        return Station.objects.filter(event=event)

class StationDetailView(generic.ListView):
    template_name = 'carbon_calculator/stations-detail.html'
    context_object_name = 'questionList'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(station=station)


def stations(request):
    global next_station
    event_name = estimator.GetEventName()
    event = Event.objects.get(name=event_name)
#    global stationList

    next_station = 1
    stationList = estimator.GetStations()
    print("len(stationList) = "+str(len(stationList)))

    for i in range(len(stationList)):
        station = Station.objects.filter(name=stationList[i]).filter(event=event)
        if (len(station))==0:
            station=Station(name=stationList[i],number=i+1,event=event)
            station.save()

    context = {'stationList':stationList}

    #stationID = 0
    #for station in stationList:
    #    tag = "STATION"+str(stationID)
    ##    stations_context[tag]=station
    #    stationID += 1

    return render(request, 'carbon_calculator/stations.html',context)

def stationdetail(request):
    global next_station
    global stationList

    # no data to proceess
    logger = logging.getLogger(__name__)
    #
    #question_list = []
    responses_list = []
    station_context = {}
    next_station = 1

    stationQuestions = estimator.GetQuestionList(next_station)
    
    if request.method == 'POST':
#        # create a form instance and populate it with data from the request:
        form = StationDetailForm(request.POST)
#        # check whether it's valid:
        if form.is_valid():
#           # process the data in form.cleaned_data as required
#            #likeIt = form.cleaned_data['like_website']
#            #if likeIt:#

            #    logger.info('Thanks for liking the web site')
            #else:
            #    logger.warning('The website likes you anyway')
            # redirect to a new URL:
            logger.info('Going to next station')
            next_station+=1
            return HttpResponseRedirect('stationdetail')
        else:
            logger.error('Form not valid, POST')
            return HttpResponseRedirect('stations-invalid-post')

    # if a GET (or any other method) we'll create a blank form
    else:
        logger.info('Form not submitted yet')  
        print('about to StationDetailForm') 
        #kwargs = {"questions":question_list, "responses":responses_list}     
        form = StationDetailForm(stationQuestions)
        #print(len(form.helper.layout[0]))
        #form.question1.label="A serious question"
        #form.helper.layout[0].append('question1')

    
    #station_context['QUESTION_LIST']=question_list
    print("len(stationList) = "+str(len(stationList)))
    station_context['STATION_TITLE'] = stationList[next_station]
    station_context['station-questions'] = stationQuestions
    next_station += 1
    station_context['form']=form
 
    return render(request, 'carbon_calculator/station-detail.html',station_context)

def example(request):
    # if this is a POST request we need to process the form data
    # Get an instance of a logger
    logger = logging.getLogger(__name__)
    
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ExampleForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            likeIt = form.cleaned_data['like_website']
            if likeIt:

                logger.info('Thanks for liking the web site')
            else:
                logger.warning('The website likes you anyway')
            # redirect to a new URL:
            return HttpResponseRedirect('stations')
        else:
            logger.error('Form not valid, POST')
            return HttpResponseRedirect('stations-invalid-post')

carbon_calculator/templates/carbon_calculator/about.html
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">

   <h1> <img src="{{EVENT_LOGO_URL}}" alt="Event logo" style="height:100px;padding-right:0">About the event</h1>
   <p>Welcome to the <strong>{{EVENT_NAME}}</strong>! We are happy to have you here, and help you take action to lower your emissions and save money.
</p>
<p>  Any information you provide will only be used to help you achieve your energy savings goal and reduce your carbon footprint, and not be used for any commercial purpose.
</p>  
 <h2>About the host organization</h2>
    <a href=http://ener-g-save.com><img src="{{HOST_LOGO_URL}}" alt="Host logo" style="height:50px;padding-right:0"></a>
</br> Ener-G-Save is a non-profit organization dedicated to helping Pioneer Valley homeowners
   cut energy loss and make their homes more comfortable and affordable  

   <h2>About the sponsor</h2>
   <a href=https://hgf.org><img src="{{SPONSOR_LOGO_URL}}" alt="Sponsor logo" style="height:50px;padding-right:0"></a>
</br>   A charitable foundation supporting community programs in Massachusetts and elsewhere.
          
    <h3><a href="{% url 'carbon_calculator:eventcalculator' %}">Continue</a></h3>

</div>

carbon_calculator/templates/carbon_calculator/create.html
<form method="POST" action="/submit">
{% for field in structure.fields  %}
   {{field.name}}: <input type="{{ field.type }}" name="{{ field.name }}"
  {% if field.required %} required {% endif %}><br>
{% endfor %}
   <input type="submit" value="Submit">
</form>

carbon_calculator/templates/carbon_calculator/eventcalculator.html
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
   <h1> <img src="{{EVENT_LOGO_URL}}"  alt="Event logo" style="height:100px;padding-right:0">
    Carbon Calculator</h1>

    <h3>Start by telling us about yourself</h2>

    <form action="eventcalculator" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Continue">
    </form>
</div>

carbon_calculator/templates/carbon_calculator/example.html
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
<h1><img src="/static/images/Full-CClogo-RGB-72dpi.jpg" alt="Cooler Concord logo" style="align:middle;width:150px;height:100px;padding-right:0">
    Action Areas</h1>

<h3>What would you like to do?</h3>

<form action="stations" method="post">
        {% csrf_token %}
        {% crispy form form.helper %}
</form>
</div>    

carbon_calculator/templates/carbon_calculator/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'carbon_calculator/style.css' %}">

<h1>Welcome to Brad's Carbon Calculator Sandbox page! (index.html)</h1>
<h2>Please choose from the following options:</h2>
<ul>
    <li><a href=eventcalculator.html>Cooler Communities Event Calculator</a></li>
</ul>

carbon_calculator/templates/carbon_calculator/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

carbon_calculator/templates/carbon_calculator/station-detail.html
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
<h2><img src="{{EVENT_LOGO_URL}}" alt="Event logo" style="align:middle;height:80px;padding-right:0">
    {{STATION_TITLE}}</h2>

    
            <h3><a href="{% url 'carbon_calculator:station'  %}">Continue</a></h3>        
</div>    

carbon_calculator/templates/carbon_calculator/stations-wforms.html
<!DOCTYPE html>
<html>
<head>
    <style>
    .grid-container {
        display: inline-grid;
        grid-template-columns: auto auto;
        grid-column-gap: 10px;
        grid-row-gap: 10px;
        background-color: white;
        padding: 10px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        border: 1px solid rgba(0, 0, 0, 0.8);
        padding: 20px;
        font-size: 50px;
        text-align: center;
      }

    </style>
</head>

{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
    <h1><img src="{{EVENT_LOGO_URL}}" alt="Event logo" style="height:80px;padding-right:0">
        Action Areas</h1>

    <h3>Choose from the following options</h3>
    
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION1}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION2}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION3}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION4}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION5}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION6}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION7}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION8}}</strong></h4>
        <h4><a href="{% url 'carbon_calculator:stationdetail' %}"><strong>{{STATION9}}</strong></h4>
    </ul>

</div>    
</html>

carbon_calculator/templates/carbon_calculator/stations.html
<!DOCTYPE html>
<html>
<head>
    <style>
    .grid-container {
        display: inline-grid;
        grid-template-columns: auto auto;
        grid-column-gap: 10px;
        grid-row-gap: 10px;
        background-color: white;
        padding: 10px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        border: 1px solid rgba(0, 0, 0, 0.8);
        padding: 20px;
        font-size: 50px;
        text-align: center;
      }

    </style>
</head>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
    <h1><img src="{{EVENT_LOGO_URL}}" alt="Event logo" style="height:80px;padding-right:0">
        Action Areas</h1>

  {% if station_list %}
    <h3>Choose from the following options</h3>   
    <ol>
    {% for station in station_list %}
    <li><h4><a href="{{ station.number }}">{{ station.name }}</a></h4></li>
     {% endfor %}
    </ol>

{% else %}
    <p>No stations are available.</p>
{% endif %}
</div>    
</html>

carbon_calculator/templates/carbon_calculator/welcome.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div  align="center">
<h1>Welcome to Brad's Carbon Calculator Sandbox page!</h1>
<h2>Please choose from the following options:{{settings.EVENT_LOGO}}</h2>
<ul>
    <li><a href="{% url 'carbon_calculator:about' %}"><strong>{{EVENT_NAME}}</strong></a>
        <img src="{{EVENT_LOGO_URL}}" alt="Event logo" style="height:75px;padding-right:0"></li>
</ul> 
</div>